#!/usr/bin/env python3
"""One-shot translator: replace hardcoded Arabic strings in the frontend
with their English equivalents. Runs idempotently — re-running is safe
because the source no longer contains the Arabic keys after the first
pass.

The mapping is ordered so that longer phrases are substituted before
shorter ones (prevents partial overlap, e.g. "إعادة تسمية" inside
"تعذّرت إعادة التسمية").
"""

from __future__ import annotations

import re
from pathlib import Path

# Comprehensive AR -> EN replacements. Add longer phrases first; the
# script re-sorts by length descending before applying so that order
# inside this list is for human readability only.
AR_TO_EN: dict[str, str] = {
    # ---- projects/page.tsx ----
    "النشاط الأخير": "Recently active",
    "الإنشاء الأخير": "Recently created",
    "الاسم (أ–ي)": "Name (A–Z)",
    "إجمالي حجم البيانات": "Total data size",
    "غير نشط بعد": "Not active yet",
    "قيد المعالجة": "Processing",
    "يوجد أخطاء": "Has errors",
    "جاهز": "Ready",
    "لا يمكن أن يكون الاسم فارغًا.": "Name cannot be empty.",
    "تعذّرت إعادة التسمية": "Failed to rename",
    "تعذّرت الأرشفة": "Failed to archive",
    "تمّت أرشفة": "Archived",
    "تراجع": "Undo",
    "تمّ استعادة": "Restored",
    "تعذّر الاستعادة": "Failed to restore",
    "تمّ حذف": "Deleted",
    "مشروع.": "project.",
    "مساحة العمل": "Workspace",
    "مشاريعك": "Your projects",
    "كل مشروع يحتفظ ببياناته وسجلّ محادثاته. مرّر فوق البطاقة لإظهار": "Every project keeps its own data and chat history. Hover a card to reveal",
    "إعادة التسمية والأرشفة والحذف. استخدم مربّعات الاختيار لأداء عمليات": "rename, archive, and delete. Use the checkboxes to perform actions",
    "على عدة مشاريع دفعة واحدة.": "on multiple projects at once.",
    "اسم مشروع جديد…": "New project name…",
    "اسم المشروع": "Project name",
    "إنشاء": "Create",
    "إخفاء الخطأ": "Dismiss error",
    "ابحث في المشاريع…": "Search projects…",
    "البحث في المشاريع": "Search projects",
    "الترتيب حسب": "Sort by",
    "النشطة": "Active",
    "المؤرشفة": "Archived",
    "محدَّد": "selected",
    "أرشفة": "Archive",
    "حذف": "Delete",
    "استعادة": "Restore",
    "مسح التحديد": "Clear selection",
    "إخفاء": "Dismiss",
    "جاري التحميل…": "Loading…",
    "جارٍ التحميل…": "Loading…",
    "لا توجد مشاريع مؤرشفة.": "No archived projects.",
    "لا توجد مشاريع تطابق": "No projects match",
    "لا توجد مشاريع بعد. أنشئ مشروعًا أعلاه للبدء.": "No projects yet. Create one above to get started.",
    "إلغاء تحديد المشروع": "Deselect project",
    "تحديد المشروع": "Select project",
    "إجراءات المشروع": "Project actions",
    "إعادة تسمية": "Rename",
    "مجموعة بيانات": "datasets",
    "محادثة": "chats",
    "أُرشف": "Archived",
    "آخر نشاط": "Active",
    "حفظ": "Save",
    "إلغاء": "Cancel",
    "الوضع": "Mode",
    "موجَّه": "Guided",
    "خبير": "Expert",
    "نشط": "Active",
    "فتح": "Open",
    "رفع بيانات": "Upload data",
    "حذف المشروع": "Delete project",
    "سيؤدّي هذا إلى حذف": "This will permanently delete",
    "نهائيًا، بما في ذلك كل البيانات وسجلّ المحادثات. لا يمكن التراجع عن ذلك.": ", including all data and chat history. This cannot be undone.",
    "للتأكيد، اكتب اسم المشروع أدناه.": "To confirm, type the project name below.",
    "نعم، متأكد": "Yes, I'm sure",
    "حذف المشاريع": "Delete projects",
    "مشروع": "project",
    "نهائيًا، بما في ذلك جميع البيانات وسجلّ المحادثات داخلها. لا يمكن التراجع عن ذلك.": ", including all data and chat history inside them. This cannot be undone.",
    "نعم، متأكد · حذف": "Yes, I'm sure · Delete",
    # template literals
    "قبل ${min} دقيقة": "${min} min ago",
    "قبل ${hr} ساعة": "${hr} hr ago",
    "قبل ${day} يوم": "${day} d ago",
    "قبل ${mo} شهر": "${mo} mo ago",
    "قبل ${yr} سنة": "${yr} y ago",
    "الآن": "Just now",
    "تمّ حذف ${res.processed.length} مشروع.": "Deleted ${res.processed.length} project(s).",
    "تمّت أرشفة ${res.processed.length} مشروع.": "Archived ${res.processed.length} project(s).",
    "تمّ استعادة ${res.processed.length} مشروع.": "Restored ${res.processed.length} project(s).",

    # ---- ArtifactDrawer.tsx ----
    "ملف البيانات": "Profile",
    "الرسوم البيانية": "Charts",
    "التنبؤات": "Predictions",
    "التجميع": "Clusters",
    "نموذج البيانات": "Data model",
    "اطلب من المساعد عمل ملف للبيانات وستظهر النتيجة هنا.": "Ask the assistant to profile the dataset — results will show here.",
    "اطلب من المساعد رسم مخطط وستظهر نتيجته هنا.": "Ask the assistant to draw a chart — results will show here.",
    "اطلب من المساعد تنبؤًا وستظهر نتائجه هنا.": "Ask the assistant for a prediction — results will show here.",
    "اطلب من المساعد تجميع الصفوف وستظهر نتائجه هنا.": "Ask the assistant to cluster rows — results will show here.",
    "سيظهر نموذج البيانات هنا حال تجهيزه.": "The data model will appear here once it's ready.",
    "تم التثبيت بالتقرير ✓": "Pinned to report ✓",
    "تم إلغاء التثبيت ✓": "Unpinned ✓",
    "تعذّر تحديث التثبيت — حاول مرة أخرى.": "Failed to update pin — try again.",
    "حذف هذا العنصر؟": "Delete this item?",
    "سيتم حذف «${a.title}» نهائيًا.": "“${a.title}” will be deleted permanently.",
    "نعم، احذف": "Yes, delete",
    "تم الحذف بنجاح ✓": "Deleted ✓",
    "تعذّر الحذف — حاول مرة أخرى.": "Failed to delete — try again.",
    "لوحة المخرجات": "Outputs",
    "مخرجات الأدوات": "Tool outputs",
    "إغلاق اللوحة": "Close panel",
    "حدث خطأ غير متوقع": "Something went wrong",
    "حاول التحديث أو إعادة المحاولة بعد قليل.": "try refreshing or retrying in a moment.",
    "جاري تجهيز ملف البيانات…": "Profiling dataset…",
    "جاري إعداد الرسم البياني…": "Building chart…",
    "جاري تدريب نموذج التنبؤ…": "Training prediction model…",
    "جاري تجميع الصفوف…": "Clustering rows…",
    "جاري تحميل نموذج البيانات…": "Loading data model…",
    "جاري تنفيذ الاستعلام…": "Running query…",
    "جاري شرح نموذج البيانات…": "Explaining data model…",
    "جاري تشغيل ${tool}…": "Running ${tool}…",
    "مثبَّت بالتقرير": "Pinned to report",
    "تثبيت بالتقرير": "Pin to report",
    "مثبَّت": "Pinned",
    "تثبيت": "Pin",
    "حذف ${artifact.title}": "Delete ${artifact.title}",
    "تأكيد": "Confirm",
    "رفض": "Reject",
    "إعادة الضبط إلى مقترح": "Reset to suggestion",
    "إعادة ضبط": "Reset",
    "لا توجد ملاحظات بعد.": "No notes yet.",
    "لا توجد بيانات بعد": "No data yet",

    # ---- ProductSidebar.tsx ----
    "إعادة تسمية المشروع": "Rename project",
    "حذف المشروع": "Delete project",
    "سيؤدي هذا إلى حذف المشروع نهائيًا مع كل محادثاته والبيانات": "This will permanently delete the project along with all its chats and",
    "المرتبطة بها. لا يمكن التراجع عن هذا الإجراء.": "associated data. This cannot be undone.",
    "جارٍ الحذف…": "Deleting…",
    "محادثة جديدة": "New chat",
    "لا توجد محادثات بعد": "No chats yet",
    "محادثة بدون عنوان": "Untitled chat",
    "إعادة تسمية المحادثة": "Rename chat",
    "حذف المحادثة": "Delete chat",
    "حذف هذه المحادثة؟ ستتم إزالة الرسائل والمخرجات.": "Delete this chat? Messages and outputs will be removed.",
    "التقرير النهائي": "Final report",
    "البيانات": "Data",
    "لا توجد بيانات بعد —": "No data yet —",
    "ارفع ملفًا": "upload a file",
    "رفع المزيد": "Upload more",

    # ---- pivot/page.tsx ----
    "شرح": "Explain",
    "جارٍ تحميل بيانات الحقول…": "Loading field metadata…",
    "ملخّصات جاهزة": "Quick summaries",
    "عوامل التصفية": "Filters",
    "الصفوف": "Rows",
    "الأعمدة": "Columns",
    "القيم": "Values",
    "العرض": "View",
    "الأعلى": "Top",
    "الأدنى": "Bottom",
    "N (0 = الكل)": "N (0 = All)",
    "المجاميع الفرعية": "Subtotals",
    "المجموع الكلي": "Grand total",
    "إسقاط القيم الفارغة من الأبعاد": "Drop empty values from dimensions",
    "الكل": "All",
    "جدول": "Table",
    "رسم بياني": "Chart",
    "جارٍ التشغيل…": "Running…",
    "تحديث": "Refresh",
    "تصدير CSV": "Export CSV",
    "صف مدخل": "input rows",
    "خلية": "cells",
    "أضف بُعدًا إلى الصفوف ومقياسًا إلى القيم لعرض الرسم البياني.": "Add a dimension to Rows and a measure to Values to render the chart.",
    "لا توجد نتائج بعد.": "No results yet.",
    "فتح أداة الجدول المحوري الكاملة": "Open full pivot table tool",
    "الصفوف والأعمدة والقيم وعوامل التصفية والمجاميع": "Rows, columns, values, filters, totals",
    "الحقول": "Fields",
    "الأبعاد": "Dimensions",
    "المقاييس": "Measures",
    "مسح": "Clear",
    "لا توجد حقول أخرى": "No other fields",
    "+ إضافة عمود…": "+ Add column…",
    "+ إضافة مقياس…": "+ Add measure…",
    "إضافة": "Add",
    "+ إضافة مقياس نسبة (CTR / هامش% / تحويل …)": "+ Add ratio measure (CTR / margin % / conversion …)",
    "النسبة = SUM(البسط) ÷ SUM(المقام)، يُعاد حسابها عند كل مستوى.": "Ratio = SUM(numerator) ÷ SUM(denominator), recomputed at every level.",
    "تُعرض دائمًا كنسبة مئوية.": "Always displayed as a percentage.",
    "البسط…": "Numerator…",
    "المقام…": "Denominator…",
    "إضافة النسبة": "Add ratio",
    "+ إضافة عامل تصفية…": "+ Add filter…",
    "قيمة": "value",
    "اضغط لإضافته كعامل تصفية": "Click to add as filter",
    "اشرح هذا الرقم": "Explain this number",
    "المجموع": "Total",

    # ---- report/page.tsx ----
    "صفحة الغلاف": "Cover page",
    "العنوان واسم البيانات وعدد الصفوف/الأعمدة والملاحظات.": "Title, dataset name, row/column count and notes.",
    "جدول الأعمدة": "Columns table",
    "نوع كل عمود وعدد القيم الموجودة والمفقودة.": "Each column's type and count of present/missing values.",
    "ملخّص رقمي": "Numeric summary",
    "جدول الإحصاءات الوصفية للأعمدة الرقمية.": "Descriptive statistics table for numeric columns.",
    "مخطّط التوزيع": "Distribution chart",
    "مدرّج تكراري لعمود رقمي واحد.": "Histogram for a single numeric column.",
    "ملاحظات الذكاء الاصطناعي": "AI insights",
    "ملخّص سردي مولَّد آليًا.": "Auto-generated narrative summary.",
    "تعذّر تحميل التقارير الأخيرة": "Failed to load recent reports",
    "تعذّر إنشاء التقرير": "Failed to generate report",
    "لا توجد بيانات نشِطة — يرجى رفع ملف أولًا.": "No active dataset — please upload a file first.",
    "اختر قسمًا واحدًا على الأقل ليُضاف إلى التقرير.": "Pick at least one section to include in the report.",
    "جاري إعداد التقرير…": "Preparing report…",
    "تم الحفظ بنجاح ✓": "Saved ✓",

    # ---- model/page.tsx ----
    "الطريقة": "Method",
    "تجميع K-Means": "K-Means clustering",
    "غابة عشوائية (Random Forest)": "Random Forest",
    "k (عدد التجمعات)": "k (number of clusters)",
    "العمود الهدف": "Target column",
    "جاري التشغيل…": "Running…",
    "تشغيل النموذج": "Run model",
    "تنبيهات حول جودة النمذجة": "Model quality alerts",
    "مفتاح الصف غير فريد —": "Row key is not unique —",
    "صف مكرّر.": "duplicate rows.",
    "قد تتأثر دقّة تقسيم التدريب/الاختبار وحجم التجمعات.": "Train/test split accuracy and cluster sizing may be affected.",
    "مفتاح الصف:": "Row key:",
    "ارفع ملف CSV أو Excel وسنبحث عن المجموعات والأنماط داخله.": "Upload a CSV or Excel file and we'll look for groups and patterns inside.",
    "جمّع الصفوف المتشابهة": "Cluster similar rows",
    "اكتشف تلقائيًا 3 شرائح طبيعية في البيانات — مفيد لتجزئة العملاء أو المنتجات.": "Automatically discover 3 natural segments in the data — great for customer or product segmentation.",
    "جد 3 مجموعات": "Find 3 groups",
    "تقسيم أدق": "Finer split",
    "الفكرة نفسها مع تقسيم إلى 5 شرائح لإبراز الفئات الأصغر.": "Same idea, split into 5 segments to surface smaller categories.",
    "جد 5 مجموعات": "Find 5 groups",
    "تنبّأ بقيمة عمود": "Predict a column",
    "درّب نموذج Random Forest للتنبؤ بالعمود المختار من بقية البيانات.": "Train a Random Forest model to predict the chosen column from the rest of the data.",
    "درّب النموذج": "Train model",
    "سيتنبّأ النموذج بـ": "The model will predict",
    ". اختر هدفًا آخر من العرض المتقدّم.": ". Choose another target from the advanced panel.",
    "اختر الطريقة وعدد التجمعات والهدف يدويًا": "Choose the method, number of clusters and target manually",
    "تم تدريب النموذج بنجاح ✓": "Model trained ✓",
    "افتح العرض الفنّي لمشاهدة مراكز التجمعات وأهمية المتغيّرات والمقاييس.": "Open the technical view to inspect cluster centers, feature importance and metrics.",

    # ---- transform/page.tsx ----
    "العملية": "Operation",
    "العمود": "Column",
    "الاسم الجديد": "New name",
    "القيمة": "Value",
    "أضف خطوة": "Add step",
    "حذف الخطوة": "Delete step",
    "جاري التطبيق…": "Applying…",
    "طبّق الخطوات": "Apply steps",
    "ارفع ملف CSV أو Excel وسنعرض أعمدته لتحويلها.": "Upload a CSV or Excel file and we'll show its columns to transform.",
    "تحويل القيم إلى حروف صغيرة": "Lowercase values",
    "اجعل كل قيم العمود بحروف صغيرة لمطابقة المسمّيات بثبات.": "Lowercase all values in this column for consistent matching.",
    "طبّق": "Apply",
    "تحويل القيم إلى حروف كبيرة": "Uppercase values",
    "اربط خطوات rename / drop / fillna / filter / uppercase / lowercase": "Chain rename / drop / fillna / filter / uppercase / lowercase steps",
    "تم تحويل العمود بنجاح ✓": "Column transformed ✓",

    # ---- clean/page.tsx ----
    "حذف الصفوف المكرّرة": "Drop duplicate rows",
    "إزالة المسافات الزائدة": "Trim whitespace",
    "تحويل النصوص إلى حروف صغيرة": "Lowercase text",
    "حذف الصفوف الفارغة": "Drop empty rows",
    "حذف الأعمدة الفارغة": "Drop empty columns",
    "ترتيب البيانات": "Tidy data",
    "حذف المكرّرات وإزالة المسافات وحذف الصفوف/الأعمدة الفارغة. خيارات آمنة لمعظم الملفات.": "Drop duplicates, trim whitespace, drop empty rows/columns. Safe defaults for most files.",
    "تطبيع النصوص": "Normalize text",
    "تحويل النصوص إلى حروف صغيرة وإزالة المسافات لمطابقة المسمّيات بين الصفوف.": "Lowercase text and trim whitespace for consistent label matching across rows.",
    "تصغير الملف": "Shrink file",
    "حذف الصفوف المكرّرة والأعمدة الفارغة لتصبح البيانات أخف وأسرع للعرض.": "Drop duplicate rows and empty columns to make the data lighter and faster to view.",
    "جاري التنفيذ…": "Running…",
    "نفّذ بهذه الخيارات": "Run with these options",
    "ارفع ملف CSV أو Excel وسنعرض لك خيارات التنظيف بضغطة واحدة.": "Upload a CSV or Excel file and we'll show one-click cleaning options.",
    "نفّذ": "Run",
    "اختر خطوات التنظيف بدقّة": "Pick cleaning steps precisely",
    "جاري التنظيف…": "Cleaning…",
    "ابدأ التنظيف": "Start cleaning",
    "تم التنظيف بنجاح ✓": "Cleaned ✓",
    "تم تنظيف بياناتك. التفاصيل الفنّية في الأسفل عند الحاجة.": "Your data is cleaned. Technical details below if needed.",
    "اكتمل التنظيف. استجابة الخادم الكاملة في الأسفل.": "Cleaning complete. Full server response below.",

    # ---- predict/page.tsx ----
    "أهم تفسيرات المتغيّرات (SHAP)": "Top feature explanations (SHAP)",
    "إسهامات المتغيّرات في توقّعات النموذج": "Feature contributions to predictions of model",
    "المختار": "the chosen one",
    "كلما زاد الشريط زاد تأثير المتغيّر على التوقّعات في المتوسّط.": "The longer the bar, the more this feature affects predictions on average.",
    "خلال الـ": "Across the next",
    "فترة القادمة يبلغ متوسّط التوقع لـ": "periods, the average forecast for",
    "مع ذروة في الفترة": "with a peak at period",
    "الفترة": "Period",
    "التوقّع": "Forecast",
    "عدد الفترات المتوقَّعة": "Number of forecast periods",
    "جاري التنبّؤ…": "Forecasting…",
    "ابدأ التنبّؤ": "Start forecasting",
    "ارفع ملف CSV أو Excel يحتوي عمودًا رقميًا وسنتنبّأ به.": "Upload a CSV or Excel file with a numeric column and we'll forecast it.",
    "ماذا تريد أن نتنبّأ به؟": "What do you want to forecast?",
    "تنبّأ بـ 3 فترات قادمة": "Forecast next 3 periods",
    "6 فترات قادمة": "Next 6 periods",
    "12 فترة قادمة": "Next 12 periods",
    "اختر الأفق الزمني والعمود بدقّة": "Choose the time horizon and column precisely",
    "عرض مخرجات النموذج": "Show model outputs",

    # ---- statistics/page.tsx ----
    "عدد الصفوف": "Row count",
    "عدد الأعمدة": "Column count",
    "أعمدة رقمية": "Numeric columns",
    "أعمدة بها قيم ناقصة": "Columns with missing values",
    "قيمة ناقصة": "missing values",
    "لا توجد قيم ناقصة.": "No missing values.",
    "أعمدة رقمية جاهزة للتحليل:": "Numeric columns ready for analysis:",
    "ارفع ملف CSV أو Excel وسنلخّص محتواه.": "Upload a CSV or Excel file and we'll summarize it.",
    "جاري الحساب…": "Calculating…",

    # ---- DataContextBar.tsx ----
    "لا توجد مجموعة بيانات مرتبطة —": "No dataset linked —",
    "ارفع ملفًا الآن": "upload one now",
    "اختر مجموعة بيانات:": "Pick a dataset:",
    "عرض ${extra} مجموعة أخرى": "Show ${extra} more datasets",
    "+ ${extra} أخرى": "+ ${extra} more",
    "طيّ": "Collapse",
    "اضغط لمعاينة أول صفوف": "Click to preview first rows",
    "معاينة": "Preview",
    "معاينة · أول": "Preview · first",
    "صفوف": "rows",
    "تعذّر تحميل المعاينة الآن.": "Failed to load preview right now.",
    "جاري تحضير المعاينة…": "Preparing preview…",
    "مجموعة البيانات فارغة.": "The dataset is empty.",

    # ---- ChatPanel.tsx ----
    "تعذّر تحميل سجل المحادثة — حاول التحديث أو إعادة المحاولة بعد قليل.": "Failed to load chat history — try refreshing or retrying in a moment.",
    "حدث خطأ أثناء المحادثة:": "Chat error:",
    "تعذّر تنفيذ الطلب": "Request failed",
    "حاول مرة أخرى.": "try again.",
    "نوع الملف غير مدعوم. اسحب ملف CSV أو TSV أو Excel أو JSON.": "Unsupported file type. Drop a CSV, TSV, Excel or JSON file.",
    "أفلت الملف للرفع": "Drop the file to upload",
    "CSV أو TSV أو Excel أو JSON": "CSV, TSV, Excel or JSON",
    "سجّل الدخول لتفعيل المحادثة مع بياناتك.": "Sign in to chat with your data.",
    "جاري تحميل المحادثة…": "Loading chat…",
    "Note · ملاحظة": "Note",
    "Pinned to report · مثبَّت بالتقرير": "Pinned to report",
    "Pin to report · ثبِّت بالتقرير": "Pin to report",

    # ---- DatasetPreviewCard.tsx ----
    "مجموعة البيانات المرتبطة بهذه المحادثة": "Dataset linked to this chat",
    "صف ×": "rows ×",
    "عمود": "cols",
    "تعذّر تحميل البيانات": "Failed to load data",
    "حاول التحديث بعد قليل.": "try refreshing in a moment.",
    "ملاحظات مفاجئة": "Surprising findings",
    "أول": "First",
    "مجموعة البيانات فارغة": "Dataset is empty",
    "لا توجد صفوف لعرضها بعد.": "No rows to show yet.",
    "جرّب أحد هذه الأسئلة": "Try one of these questions",

    # ---- ModeAware.tsx ----
    "متقدّم": "Advanced",
    "حوّل هذا المشروع إلى وضع الخبير": "Switch this project to Expert mode",
    "اعرض التفاصيل التقنية": "Show technical details",
    "افتح في وضع الخبير": "Open in Expert mode",
    "تقني": "Technical",
    "ارفع ملف CSV أو Excel للبدء": "Upload a CSV or Excel file to get started",
    "ارفع مجموعة بيانات": "Upload a dataset",

    # ---- InteractiveTable.tsx ----
    "ابحث في الصفوف…": "Search rows…",
    "البحث في صفوف الجدول": "Search table rows",
    "صف": "rows",
    "الصف": "Row",
    "انقر للسؤال": "click to ask",
    "لا توجد صفوف مطابقة.": "No matching rows.",

    # ---- Gauge.tsx ----
    "ثقة مرتفعة": "High confidence",
    "ثقة متوسطة": "Medium confidence",
    "ثقة منخفضة": "Low confidence",
    "نسبة الثقة": "Confidence",
    "من 100,": "of 100,",

    # ---- Charts.tsx ----
    'نوع المخطّط &quot;{payload.chart}&quot; غير مدعوم في العرض.': 'Chart type &quot;{payload.chart}&quot; is not supported in this view.',
    "لا توجد أعمدة رقمية.": "No numeric columns.",
    "لا تتوفّر ارتباطات.": "No correlations available.",

    # ---- ProjectWorkspace.tsx ----
    "لم يُعثر على المشروع.": "Project not found.",

    # ---- Spinner.tsx, EmptyState.tsx, OpenQuestionsBar.tsx, chat/page.tsx ----
    "أسئلة مفتوحة عن بياناتك": "Open questions about your data",
    "جاري فتح محادثة المشروع…": "Opening project chat…",

    # ---- fields/page.tsx ----
    "بُعد": "Dimension",
    "مقياس": "Measure",
    "معرّف": "Key",
    "تاريخ": "Date",
    "رقم": "Number",
    "عدد صحيح": "Integer",
    "عملة": "Currency",
    "نسبة مئوية": "Percent",
    "نص": "Text",
    "تصفية": "Filter",
    "كل الأعمدة": "All columns",
    "المقاييس": "Measures",
    "الأبعاد": "Dimensions",
    "التواريخ": "Dates",
    "المعرّفات": "Keys",
    "من أصل": "of",
    "مخصّص": "custom",
    "الدور": "Role",
    "التجميع الافتراضي": "Default aggregation",
    "التنسيق": "Format",
    "المسمّى": "Label",
    "الوصف": "Description",
    "الفرز حسب": "Sort by",
    "مرئي": "Visible",
    "ملاحظات": "Notes",
    "إعادة تعيين": "Reset",
    "قيمة فريدة": "unique values",
    "عدد المنازل العشرية للعمود": "Decimal places for column",
    "مسمّى العمود": "Column label",
    "ماذا يمثّل هذا العمود؟": "What does this column represent?",
    "وصف العمود": "Column description",
    "الفرز حسب للعمود": "Sort-by for column",
    "— الافتراضي —": "— Default —",
    "إخفاء العمود من القوائم دون حذفه": "Hide column from menus without deleting",
    "إظهار العمود": "Show column",
    "تلقائي": "auto",

    # ---- admin/support/page.tsx ----
    "إدارة": "Admin",
    "صندوق الدعم": "Support inbox",
    "تُحفظ كل رسالة تُرسَل عبر نموذج التواصل هنا لتتمكّن من المتابعة حتى عند تعذّر إرسال البريد.": "Every message sent through the contact form is saved here so you can follow up even if email delivery fails.",
    "إظهار غير المُعالَجة فقط": "Show unresolved only",
    "عرض": "Showing",
    "من": "of",
    "مُعالَجة": "Resolved",
    "جاري الحفظ…": "Saving…",
    "إعادة فتح": "Reopen",
    "وضع علامة مُعالَجة": "Mark resolved",
    "تحميل المزيد": "Load more",
    "متبقية": "remaining",
    "(بدون اسم)": "(no name)",
    "الصندوق فارغ — لا رسائل مفتوحة.": "Inbox is empty — no open messages.",
    "لا توجد رسائل دعم بعد.": "No support messages yet.",

    # ---- visualize/page.tsx ----
    "تلقائي (افتراضي الحقل)": "Auto (field default)",
    "مجموع": "Sum",
    "متوسط": "Avg",
    "عدد": "Count",
    "عدد مميّز": "Distinct count",
    "أصغر قيمة": "Min",
    "أكبر قيمة": "Max",
    "وسيط": "Median",
    "اختر عمودًا رقميًا، أو اتركه لتلخيص كل الأعمدة الرقمية": "Pick a numeric column, or leave blank to summarize all numeric columns",
    "الخريطة الحرارية تستخدم كل الأعمدة الرقمية": "Heatmap uses all numeric columns",
    "نوع الرسم": "Chart type",
    "أعمدة": "Bar",
    "خطّي": "Line",
    "مبعثر": "Scatter",
    "دائري": "Pie",
    "مدرّج تكراري": "Histogram",
    "صندوقي": "Box",
    "خريطة ارتباط": "Heatmap",
    "عمود X": "X column",
    "(غير مستخدم)": "(unused)",
    "عمود Y": "Y column",
    "التجميع للقيم Y": "Aggregation for Y",
    "جارٍ الرسم…": "Drawing…",
    "ارسم الشكل": "Draw chart",
    "تشخيصات الخبراء": "Expert diagnostics",
    "التشخيص": "Diagnostic",
    "البواقي مقابل المتوقّع": "Residuals vs fitted",
    "رسم Q–Q (الطبيعية)": "Q–Q plot (normality)",
    "الارتباط الذاتي (ACF)": "Autocorrelation (ACF)",
    "الارتباط الذاتي الجزئي (PACF)": "Partial autocorrelation (PACF)",
    "التأخّرات": "Lags",
    "جارٍ الحساب…": "Calculating…",
    "تشغيل التشخيص": "Run diagnostic",
    "ملخص": "Summary",
    "العمود المراد عرضه": "Column to show",
    "إظهار التوزيع": "Show distribution",
    "مدرّج تكراري لكيفية انتشار قيم هذا العمود — مفيد لاكتشاف الانحراف أو القيم الشاذّة.": "Histogram of how values are spread in this column — useful for spotting skew or outliers.",
    "عرض المدرّج التكراري": "Show histogram",
    "إظهار حصة المجموع": "Show share of total",
    "رسم دائري للفئات في هذا العمود.": "Pie chart of categories in this column.",
    "عرض الرسم الدائري": "Show pie chart",
    "ما الذي يتحرك معًا": "What moves together",
    "خريطة ارتباط حرارية عبر كل الأعمدة الرقمية. لا يحتاج اختيار عمود.": "Correlation heatmap across all numeric columns. No column selection needed.",
    "عرض الخريطة الحرارية": "Show heatmap",
    "اكتشاف القيم الشاذة": "Detect outliers",
    "ملخص رسم صندوقي لكل عمود رقمي دفعةً واحدة.": "Box plot summary for every numeric column at once.",
    "عرض الرسم الصندوقي": "Show box plot",
    "اختر أي نوع رسم بياني وحدّد x / y يدويًا": "Choose any chart type and pick x / y manually",
    "عرض الأرقام الأساسية": "Show core numbers",

    # ---- dashboard/page.tsx ----
    "مؤشّرات الأداء التنفيذية": "Executive KPIs",
    "الاتجاهات عبر الزمن": "Trends over time",
    "التقسيم": "Segmentation",
    "التشغيلي": "Operational",
    "أخرى": "Other",
    "هذا المقياس": "this metric",
    "تعذّر حساب ${friendly} للنطاق الحالي.": "Unable to compute ${friendly} for the current range.",
    "إجمالي ${friendly} عبر الصفوف ضمن النطاق.": "Total ${friendly} across rows in the current range.",
    "نسبة ${friendly} عبر الصفوف ضمن النطاق.": "Percentage ${friendly} across rows in the current range.",
    "عدد ${friendly} عبر الصفوف ضمن النطاق.": "Count ${friendly} across rows in the current range.",
    "القيمة المجمَّعة لـ ${friendly} عبر الصفوف ضمن النطاق.": "Aggregated value of ${friendly} across rows in the current range.",
    "لوحة المعلومات": "Dashboard",
    "بياناتك في لمحة": "Your data at a glance",
    "لوحة معلومات البيانات": "Data dashboard",
    "مؤشّرات واتجاهات وتقسيمات تلقائية. استخدم الفلاتر في الأعلى لتصفية كل البلاطات معًا.": "Auto KPIs, trends and segments. Use the filters at the top to slice every tile at once.",
    "مواصفات بلاطات محفوظة فوق محرّك التجميع المركزي. تمرّ فلاتر الصفحة عبر نفس SUM/AVG المستخدَم في pivot وvisualize والمحادثة.": "Saved tile specs over the central aggregation engine. Page filters flow through the same SUM/AVG used in pivot, visualize and chat.",
    "جاري التحديث…": "Refreshing…",
    "إعادة الضبط للاقتراحات التلقائية": "Reset to auto suggestions",
    "الفلاتر": "Filters",
    "من": "from",
    "إلى": "to",
    "مسح الفلاتر": "Clear filters",
    "تنبيهات النمذجة": "Modeling alerts",
    "تعذّر إيجاد دقّة فريدة لهذا الجدول — يحتوي على": "Couldn't find a unique grain for this table — it has",
    "صفًا مكرّرًا.": "duplicate rows.",
    "قد تتسبّب التجميعات بعدّ مزدوج بدون مفتاح أساسي نظيف.": "Aggregations may double-count without a clean primary key.",
    "الدقّة:": "Grain:",
    "لا توجد بلاطات بعد. استخدم صفحة": "No tiles yet. Use the",
    "المحور": "Pivot",
    "أو": "or",
    "التصوّر": "Visualize",
    "للبناء، أو انقر &quot;إعادة الضبط&quot; لاقتراح بلاطات تلقائيًا.": "page to build, or click &quot;Reset&quot; to auto-suggest tiles.",
    "إزالة البلاطة": "Remove tile",
    "تفسير": "Explain",
    "عرض JSON": "Show JSON",
    "تفسير هذه البلاطة": "Explain this tile",
    "فتح في المحور": "Open in Pivot",
    "تفصيل →": "Drill down →",
    "مقياس": "Measure",
    "إغلاق": "Close",
    "الصيغة": "Formula",
    "الفلاتر النشِطة": "Active filters",
    "ساهم": "Contributed",
    "صف.": "rows.",
    "عيّنة من الصفوف المساهِمة": "Sample of contributing rows",

    # ---- GuidedPredictionWizard.tsx ----
    "حدث خطأ أثناء التنبؤ. الرجاء المحاولة مرة أخرى.": "An error occurred during the forecast. Please try again.",
    "المرحلة 1 من 3 · المسح": "Step 1 of 3 · Scanning",
    "المرحلة 2 من 3 · الأسئلة التوضيحية": "Step 2 of 3 · Clarifying questions",
    "المرحلة 3 من 3 · حساب التنبؤ": "Step 3 of 3 · Computing forecast",
    "النتيجة": "Result",
    "تنبيه": "Alert",
    "AXIOM · التنبؤ الموجّه": "AXIOM · Guided forecast",
    "نقوم الآن بفحص بياناتك": "We're scanning your data",
    "لتحديد أفضل المؤشرات للتنبؤ بها.": "to identify the best metrics to forecast.",
    "نبحث عن أعمدة الزمن، الهدف الرقمي والعوامل المؤثرة…": "Looking for time columns, numeric targets and driving factors…",
    "حجم البيانات": "Data volume",
    "جودة البيانات": "Data quality",
    "قوة الإشارة": "Signal strength",
    "تغطية الزمن": "Time coverage",
    "ما اكتشفناه:": "What we found:",
    "سنتنبأ بـ": "We'll forecast",
    "عبر الزمن باستخدام عمود": "over time using column",
    "بناءً على": "based on",
    "عوامل مؤثرة:": "driving factors:",
    "بناءً على البيانات المتاحة.": "based on the available data.",
    "السؤال": "Question",
    "← السابق": "← Back",
    "صفًا": "rows",
    "تشغيل التنبؤ →": "Run forecast →",
    "التالي →": "Next →",
    "ثقة مبدئية قبل التشغيل (تتحدث بعد التنبؤ):": "Preliminary confidence before running (updates after the forecast):",
    "نعم": "Yes",
    "لا": "No",
    "جاري تشغيل النموذج للتنبؤ بـ": "Running the model to forecast",
    "نقوم بدمج النموذج الإحصائي مع تحليل العوامل وحساب درجة الثقة.": "We're combining the statistical model with driver analysis and computing the confidence score.",
    "المحاولة مجددًا": "Try again",

    # ---- GuidedPredictionCard.tsx ----
    "تنبؤ موجّه": "Guided forecast",
    "سلاسل زمنية": "time series",
    "نموذج عوامل": "factor model",
    "تشغيل تنبؤ جديد": "Run new forecast",
    "التوقع التالي": "Next forecast",
    "متوسط التوقعات": "Average forecast",
    "الحد الأدنى": "Lower bound",
    "الحد الأعلى": "Upper bound",
    "الأفق (فترات)": "Horizon (periods)",
    "التوقع الأساسي": "Baseline forecast",
    "جودة التوافق R²": "R² goodness of fit",
    "متوسط الخطأ المطلق": "Mean absolute error",
    "مرتفعة": "high",
    "متوسطة": "medium",
    "منخفضة": "low",
    "ثقة": "Confidence",
    "التاريخ والتوقع": "History & forecast",
    "أهمية العوامل": "Driver importance",

    # ---- project/[id]/report/page.tsx ----
    "No chat session selected. / لم تُحدَّد جلسة محادثة.": "No chat session selected.",
    "Final report · التقرير النهائي": "Final report",
    "pinned · مثبَّت": "pinned",
    "of ${totalArtifacts} total · من ${totalArtifacts} الكلّي": "of ${totalArtifacts} total",
    "Pinned only · المثبَّت فقط": "Pinned only",
    "Back to chat · رجوع للمحادثة": "Back to chat",

    # ---- pivot/page.tsx residuals ----
}


def build_pattern() -> re.Pattern[str]:
    keys = sorted(AR_TO_EN.keys(), key=len, reverse=True)
    escaped = [re.escape(k) for k in keys]
    return re.compile("|".join(escaped))


def main() -> int:
    root = Path(__file__).resolve().parent.parent / "frontend" / "src"
    pattern = build_pattern()
    files = []
    for path in root.rglob("*.tsx"):
        if "/tests/" in str(path) or "/messages/" in str(path):
            continue
        files.append(path)
    for path in root.rglob("*.ts"):
        if "/tests/" in str(path) or "/messages/" in str(path):
            continue
        files.append(path)

    total_replaced = 0
    files_changed = 0
    for path in files:
        text = path.read_text(encoding="utf-8")
        new_text, n = pattern.subn(lambda m: AR_TO_EN[m.group(0)], text)
        if n > 0:
            path.write_text(new_text, encoding="utf-8")
            files_changed += 1
            total_replaced += n
            print(f"  {path.relative_to(root.parent.parent)}: {n} substitutions")
    print(f"\nDone. {files_changed} files changed, {total_replaced} substitutions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
